### ISSUE TITLE
Build fails due to kj/compat/http-test.c and http.c

### ISSUE THREAD

**Issue by mrdomino** [sandstorm-io/ekam#11]
I get build errors like this:

```
compile: kj/compat/http-test.c++
  /ekam-provider/canonical/kj/compat/http-test.c++:544:3: error: no matching constructor for initialization
    of 'const kj::(anonymous namespace)::HttpRequestTestCase'
```

To reproduce:

1. Provision an Ubuntu 16.04.1 VM from <https://vultr.com/>.
2. Install Sandstorm install deps. (I used clang-3.8.)
3. Clone sandstorm and run `make deps` with `deps -> ..`.
4. Build ekam with `make CXX=clang++`.

(I know of no way that step 3 would be important, but I don't want to spend the time to reproduce with just ekam, and I want to capture exactly what I did.)

Note that if you edit the ekam Makefile to use C++14 instead of C++11, the build succeeds.

@dwrensha reports that this doesn't happen with clang-3.8 on Fedora, or on Arch.

**Comment by dwrensha** [comment]
Update: I can in fact reproduce this problem with clang-3.8 on Fedora. My Sandstorm build succeeds because it uses different CXXFLAGS.
