### ISSUE TITLE
ekam build seems to need c++14, not just c++11?

### ISSUE THREAD

**Issue by abliss** [sandstorm-io/ekam#13]
I'm certainly no expert on the difference, but:
1) my build fails with an inscrutable error about a "body of constexpr function … not a return-statement"
2) http://stackoverflow.com/questions/40604838/min-max-step-function-and-body-of-constexpr-function-not-a-return-statement suggests "The rules for constexpr functions were very strict in C++11. ... The rules were relaxed considerably in C++14."
3) Changing `-std=c++11` to `-std=c++14` in Makefile seems to make the problem go away.

This is with gcc 5.4.0

**Comment by dwrensha** [comment]
I think this is the same as https://github.com/sandstorm-io/ekam/issues/11.

What about `-std=gnu++11`?

**Comment by abliss** [comment]
For reference, here are some of the errors with c++11.
```
/ekam-provider/canonical/kj/compat/http-test.c++:863:1: error: could not convert '{"HTTP/1.1 200 OK\015\012Content-Length: 7\015\012\015\012", 200, "OK", <brace-enclosed initializer list>(), 7, {
[FAILED ] compile: kj/compat/http.c++
/ekam-provider/canonical/kj/compat/http.c++: In instantiation of 'static constexpr bool kj::{anonymous}::FastCaseCmp<first, rest ...>::apply(const char*) [with char first = '1'; char ...rest = {}
/ekam-provider/canonical/kj/compat/http.c++:1185:70:   recursively required from 'static constexpr bool kj::{anonymous}::FastCaseCmp<first, rest ...>::apply(const char*) [with char first = 'O'; c
/ekam-provider/canonical/kj/compat/http.c++:1185:70:   required from 'static constexpr bool kj::{anonymous}::FastCaseCmp<first, rest ...>::apply(const char*) [with char first = 'f'; char ...rest
/ekam-provider/canonical/kj/compat/http.c++:1203:38:   required from 'constexpr bool kj::{anonymous}::fastCaseCmp(const char*) [with char ...chars = {'f', 'O', 'o', 'B', '1'}]'
/ekam-provider/canonical/kj/compat/http.c++:1207:55:   required from here
/ekam-provider/canonical/kj/compat/http.c++:1191:3: error: body of constexpr function 'static constexpr bool kj::{anonymous}::FastCaseCmp<first, rest ...>::apply(const char*) [with char first = '
   }
```

**Comment by abliss** [comment]
`-std=gnu++11` seems to have the same problem.

**Comment by kentonv** [comment]
Oops, that appears to be an issue in Cap'n Proto code. Specifically, some code I added fairly recently which I guess I never tested in C++11 mode.

I'm tempted to declare that Cap'n Proto now requires C++14, since there's some pretty big improvements that I'd like to rely on going forward...

**Comment by mrdomino** [comment]
FWIW bazel still seems to compile as C++11 by default. Maybe not that big a deal though -- it's easy enough to set custom compile flags in a bazel.rc or something.
