### ISSUE TITLE
Print a message when a continuous build has finished building all targets.

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/ekam#15]
I'm finding myself resorting to `top` to tell whether the build for sandstorm is actually completed; it would be nice if `ekam -c` would print out a message when it's built the last target.

**Comment by kentonv** [comment]
Hmm, are you finding the color coding hard to distinguish? Steps that are still running are colored purple, whereas finished steps are blue (successful non-tests), green (successful tests), or red (failed).

**Comment by zenhack** [comment]
I noticed the purple thing some time after having posted this. I *can* tell the difference, once I'm looking for it, but I am slightly blue-purple colorblind, so perhaps that has something to do with why it didn't jump out at me at first. It occurs to me that green-red may cause problems for other folks as well, though not me personally.

Also, while I'm not using it as much anymore, color-coding is something of a no-go with my smaller laptop: 

https://zenhack.net/2015/07/25/working-outside.html

(The screen is black-and-white when the backlight is off).

**Comment by zenhack** [comment]
One simple way to improve this would be to just add the status (as text) in front of the output, like:

```
[DONE] compile: foo.c
[DONE] compile: bar.c
[....] compile: baz.c
```

I also think adding a `Build finished` message at the end would be useful; even when I'm looking for the color coding, it's a bit easier at a glance to look for the presence of something than the absence of something (like a purple keyword or `[....]` or whatever it ends up being). In a non-continuous build, the return to the prompt plays this role.

**Comment by kentonv** [comment]
Yeah I agree some non-color indicators would be a good idea. Maybe we can use:

* ↺ Step in progress. (Some day we can be fancy and animate it but that'll require a lot more code.)
* &nbsp;&nbsp;&nbsp; Step complete (blank space, no icon)
* ✔ Test passed
* ✘ Test/step failed

Thoughts?

**Comment by kentonv** [comment]
(All those code points work great in my terminal FWIW.)
