### ISSUE TITLE
echo is missing the -e option

### ISSUE THREAD

**Issue by ryanmjacobs** [sandstorm-io/ekam#2]
https://github.com/sandstorm-io/ekam/blob/master/Makefile#L34

The `-e` option allows `echo` to interpret `\n`, `\t`, etc. So use `echo -e "======\nSUCCESS\n====="` instead.

**Comment by kentonv** [comment]
Do you observe the output being incorrect on your machine? If so, what distro?

`-e` is actually a non-standard option implemented by Bash. make invokes `/bin/sh` which on Debian-derived distros is actually Dash, not Bash. Dash's `echo` does not support `-e` (it will literally print `-e` if you try to pass this flag), but it interprets escapes by default (POSIX unhelpfully leaves it implementation-defined whether escapes are interpreted by default). So using `-e` here would actually produce incorrect output, whereas currently it is correct (on my machine).

Weirdly, on OSX, where `/bin/sh` is actually Bash, when invoked as `sh` it exhibits Dash-like behavior in this respect, but on Debian if I symlink `/bin/sh` to `bash` I get Bash behavior even when invoked as `sh`. So I suppose if you're using a distro where `/bin/sh` is Bash, you might see the wrong output?

Sadly, using `/bin/echo` won't solve this problem as on some platforms (OSX) it does not implement `-e` either.

So `-e` definitely won't work, but my current solution works on all machines I own. If it doesn't work on yours, maybe I just need to write multiple `echo` statements.

**Comment by ryanmjacobs** [comment]
I'm running Arch Linux which has its `/bin/sh` symlinked to `bash`. And you're right, it looks like `-e` is a BASH-specific option. On a Ubuntu system running `/bin/sh` symlinked to `dash`, it works without the `-e` option.

Supposedly, running `bash` with the program name `sh` will cause it to use `set -o posix` to enable more posix-like features. But alas, this still doesn't fix `echo`'s behavior across all systems.

There are threes ways I think this could be fixed:
 a) Break up the `echo` into multiple calls.
 b) Use `printf` instead, e.g. `printf "=====\nsomething\n=====` works fine
 c) Detect what shell is running with `sh --version`, then set a variable ECHO to either `echo` or `echo -e` and use `$(ECHO) "====\nsomething\n===="

Honestly, I don't think it's worth the effort but if you really wanted it to look the same on all systems, I would go with `printf`. That would require minimal changes.

**Comment by kentonv** [comment]
Oh, duh, printf! I actually figured this out once before and then forgot -- the Sandstorm Makefile only uses printf for exactly this reason. Durr. Thanks for the reminder.

**Comment by ryanmjacobs** [comment]
Ahh, no problem. :grimacing:
